name: Deploy WordPress Theme

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy Theme
      run: |
        rsync -azP --delete-after --exclude='.git*' --exclude='.github*' . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }}:"/2 - www/dev/WP_blank.5pectre.com/wp-content/themes"
