name: Deploy WordPress Theme

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up SSH key
      run: |
        echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
        echo "SSH_ADDRESS: ${{ secrets.SSH_ADDRESS }}"
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.SSH_ADDRESS }} >> ~/.ssh/known_hosts
        
    - name: Deploy Theme
      run: |
        rsync -azP --delete-after --exclude='.git*' --exclude='.github*' ."2 - www/WP_blank.5pectre.design_2021/wp-content/themes" ${{ secrets.SSH_USER }}@${{ secrets.SSH_ADDRESS }}:/
        
    - name: Clear SSH key
      run: rm -f ~/.ssh/workflow
