name: Deploy WordPress Theme

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        ls
        echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 -d > /homepages/13/d829753805/htdocs/.ssh/workflow
        chmod 600 /homepages/13/d829753805/htdocs/.ssh/workflow
        ssh-keyscan -t rsa ${{ secrets.SERVER_ADDRESS }} >> /homepages/13/d829753805/htdocs/.ssh/workflow

    - name: Deploy Theme
      run: |
        rsync -azP --delete-after --exclude='.git*' --exclude='.github*' . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }}:"/2 - www/dev/WP_blank.5pectre.com/wp-content/themes"

    - name: Clear SSH key
      run: rm -f ~/.ssh/workflow
