name: Deploy WordPress Theme

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Find Keys
      run: find / -name "workflow"
      
    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 -d > ~/.ssh/workflow
        ls
        chmod 600 ~/.ssh/workflow
        ssh-keyscan -t rsa ${{ secrets.SERVER_ADDRESS }} >> ~/.ssh/known_hosts

    - name: Deploy Theme
      run: |
        rsync -azP --delete-after --exclude='.git*' --exclude='.github*' . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }}:"/2 - www/dev/WP_blank.5pectre.com/wp-content/themes"

    - name: Clear SSH key
      run: rm -f ~/.ssh/workflow
